insert into genres (category, genres) values ('Лёгкое чтение', 'Фантастика');
insert into genres (category, genres) values ('Лёгкое чтение', 'Боевики');
insert into genres (category, genres) values ('Лёгкое чтение', 'Детективы');
insert into genres (category, genres) values ('Лёгкое чтение', 'Триллер');
insert into genres (category, genres) values ('Лёгкое чтение', 'Крутой детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Иронический детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Про маньяков');
insert into genres (category, genres) values ('Лёгкое чтение', 'Шпионский детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Криминальный детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Классический детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Политический детектив');
insert into genres (category, genres) values ('Лёгкое чтение', 'Фэнтези');
insert into genres (category, genres) values ('Лёгкое чтение', 'Романы');
insert into genres (category, genres) values ('Лёгкое чтение', 'Ужасы');
insert into genres (category, genres) values ('Лёгкое чтение', 'Приключения');
insert into genres (category, genres) values ('Серьёзное чтение', 'Биографии');
insert into genres (category, genres) values ('Деловая литература', 'Управление экономикой');
insert into genres (category, genres) values ('Деловая литература', 'Карьера');
insert into genres (category, genres) values ('Деловая литература', 'Маркетинг, PR, реклама');
insert into genres (category, genres) values ('Деловая литература', 'Финансы');
insert into genres (category, genres) values ('Деловая литература', 'Бизнес-справочники');
insert into genres (category, genres) values ('Деловая литература', 'Личные финансы');
insert into genres (category, genres) values ('Деловая литература', 'Менеджмент');
insert into genres (category, genres) values ('Деловая литература', 'Зарубежная деловая литература');
insert into genres (category, genres) values ('Деловая литература', 'Личная эффективность');
insert into genres (category, genres) values ('Деловая литература', 'Тайм-менеджмент');
insert into genres (category, genres) values ('Деловая литература', 'Малый бизнес');
insert into genres (category, genres) values ('Деловая литература', 'Продажи');
insert into genres (category, genres) values ('Деловая литература', 'Стартапы и создание бизнеса');
insert into genres (category, genres) values ('Деловая литература', 'Корпоративная культура');
insert into genres (category, genres) values ('Деловая литература', 'Банковское дело');
insert into genres (category, genres) values ('Деловая литература', 'Логистика');
insert into genres (category, genres) values ('Деловая литература', 'Недвижимость');
insert into genres (category, genres) values ('Деловая литература', 'Интернет-бизнес');
insert into genres (category, genres) values ('Деловая литература', 'Ораторское искусство');
insert into genres (category, genres) values ('Деловая литература', 'Привлечение клиентов');
insert into genres (category, genres) values ('Деловая литература', 'Делопроизводство');
insert into genres (category, genres) values ('Деловая литература', 'Переговоры');
insert into genres (category, genres) values ('Деловая литература', 'О бизнесе популярно');
insert into genres (category, genres) values ('Деловая литература', 'Ценные бумаги / инвестиции');
insert into genres (category, genres) values ('Деловая литература', 'Бухучет / налогообложение ');
insert into genres (category, genres) values ('Деловая литература', 'Российская практика');
insert into genres (category, genres) values ('Деловая литература', 'Истории успеха');
insert into genres (category, genres) values ('Деловая литература', 'Интернет-маркетинг');
insert into genres (category, genres) values ('Деловая литература', 'Лидерство');
insert into genres (category, genres) values ('Деловая литература', 'Проектный менеджмент');
insert into genres (category, genres) values ('Деловая литература', 'Управление качеством');
insert into genres (category, genres) values ('Деловая литература', 'Финансовый менеджмент');
insert into genres (category, genres) values ('Деловая литература', 'Управление персоналом');
insert into genres (category, genres) values ('Деловая литература', 'Бизнес-процессы');
insert into genres (category, genres) values ('Деловая литература', 'Управление бизнесом');
insert into genres (category, genres) values ('Драматургия', 'Античная драма');
insert into genres (category, genres) values ('Драматургия', 'Комедия');
insert into genres (category, genres) values ('Драматургия', 'Сценарий');
insert into genres (category, genres) values ('Драматургия', 'Драма, пьеса');